# Site settings
author: Oscar Vuong
title: Road to Development
header-img: img/home-bg.png
email: oscarvuong@gmail.com
copyright_name: Oscar Vuong
description: > # this means to ignore newlines until "baseurl:"
  Watch me learn!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  o-vuong

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
